image: gitpod/workspace-full:latest

tasks:
  - name: install go-task
    init: go install github.com/go-task/task/v3/cmd/task@latest
  - name: install python 3.10.x
    init: pyenv install 3.10.7 && pyenv global 3.10.7
  - name: install mypy
    init: python3 -m pip install mypy pylint yapf

ports:
  # jupyter
  - port: 9000-9100
    onOpen: ignore
  - port: 40000-50000
    onOpen: ignore

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
