image: gitpod/workspace-full:latest

tasks:
  - name: install go-task
    init: go install github.com/go-task/task/v3/cmd/task@latest

ports:
  # jupyter
  - port: 9000-9100
    onOpen: ignore
  - port: 40000-50000
    onOpen: ignore

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
