version: "3"

tasks:
  init:
    cmds:
      - gp open main.py
  jupyter:
    cmds:
      - gp open main.ipynb
  run:
    cmds:
      - python3 main.py
  version:
    cmds:
      - python3 -V
  clean:
    cmds:
      - rm -f *.py
      - rm -f *.ipynb
