version: "3"

tasks:
  init:
    cmds:
      - touch main.py
  jupyter:
    cmds:
      - touch main.ipynb
  fmt:
    cmds:
      - yapf -i main.py
  vet:
    cmds:
      - cmd: pylint main.py
        ignore_error: true
      - cmd: mypy main.py
        ignore_error: true
  run:
    cmds:
      - python3 main.py
  version:
    cmds:
      - python3 -V
  clean:
    cmds:
      - rm -f *.py
      - rm -f *.ipynb
